/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <string.h>
#include "usart.h"
#include "i2c.h"
#include "systick.h"
#include "bme280.h"
#include "exti.h"


int main(void)
{
    usart2_init();
    systick_init();
    i2c1_init();
    exti_init();

    if(bme280_init() != BME280_STATUS_OK) {
        usart2_write_bytes((uint8_t*)"bme280 init fail\r\n", 18);
        while(1){}
    }

    usart2_write_bytes((uint8_t*)"bme280 init ok\r\n", 16);

    char    buf[64];
    int     len;

    while(1) {
        if(exti_get_print_flag()) {
            bme280_read_raw();
            bme280_compensate();

            const bme280_data_t *d = bme280_get_data();

            len = sprintf(buf,
                          "T:%ld.%02ld C  P:%lu.%02lu hPa  H:%lu.%02lu%%\r\n",
                          (long)(d->temperature / 100),
                          (long)(d->temperature % 100),
                          (unsigned long)(d->pressure    / 100),
                          (unsigned long)(d->pressure    % 100),
                          (unsigned long)(d->humidity    / 100),
                          (unsigned long)(d->humidity    % 100));

            usart2_write_bytes((uint8_t*)buf, (size_t)len);
            exti_clear_print_flag();
        }
    }
}
